#ifdef USE_SDL2
  #include <card_game.h>
  #include <font.h>
  #ifndef SDL_API_H
    #define SDL_API_H
    #define REDRAW_NONE   0
    #define REDRAW_IMAGE  1
    #define SET_RENDER_DRAW_COLOR(RENDERER, RGBA) \
            SDL_SetRenderDrawColor( \
              RENDERER, \
              (unsigned char)(RGBA[0] != ZERO_RGB ? RGBA[0] : 0x00), \
              (unsigned char)(RGBA[1] != ZERO_RGB ? RGBA[1] : 0x00), \
              (unsigned char)(RGBA[2] != ZERO_RGB ? RGBA[2] : 0x00), \
              (unsigned char)(RGBA[3] != ZERO_RGB ? RGBA[3] : 0x00) \
            )
    void vSDL_MainInit();
    void vSDL_MainLoop(int *pbRunning, SDL_Event *pSDL_Event, SDL_Renderer *pSDL_Renderer, PSTRUCT_DECK pstDeck, PSTRUCT_MONSTER pastMonsters, int iMonsterCt);
    void vSDL_MainQuit(void);
    int bAreCoordsInSDL_Rect( SDL_Rect *pSDL_RECT, int iX, int iY );
    void vSDL_DrawText(SDL_Renderer *pSDL_Renderer, const char *szTxt, int iX, int iY, SDL_Color stCol);
    void vSDL_DrawTable(SDL_Renderer *pSDL_Renderer,
                    PSTRUCT_DECK pstDeck,
                    PSTRUCT_MONSTER pastMonsters,
                    int iMonsterCt);
    void vSDL_DrawHUD(SDL_Renderer *pSDL_Renderer, PSTRUCT_PLAYER pstPlayer);

    typedef struct { Uint32 type; const char *name; } SDLEventName;
   
    static const SDLEventName gEventNames[] = {
        { SDL_FIRSTEVENT, "SDL_FIRSTEVENT" },
        { SDL_QUIT, "SDL_QUIT" },
        { SDL_APP_TERMINATING, "SDL_APP_TERMINATING" },
        { SDL_APP_LOWMEMORY, "SDL_APP_LOWMEMORY" },
        { SDL_APP_WILLENTERBACKGROUND, "SDL_APP_WILLENTERBACKGROUND" },
        { SDL_APP_DIDENTERBACKGROUND, "SDL_APP_DIDENTERBACKGROUND" },
        { SDL_APP_WILLENTERFOREGROUND, "SDL_APP_WILLENTERFOREGROUND" },
        { SDL_APP_DIDENTERFOREGROUND, "SDL_APP_DIDENTERFOREGROUND" },
        { SDL_LOCALECHANGED, "SDL_LOCALECHANGED" },
        { SDL_DISPLAYEVENT, "SDL_DISPLAYEVENT" },
        { SDL_WINDOWEVENT, "SDL_WINDOWEVENT" },
        { SDL_SYSWMEVENT, "SDL_SYSWMEVENT" },
        { SDL_KEYDOWN, "SDL_KEYDOWN" },
        { SDL_KEYUP, "SDL_KEYUP" },
        { SDL_TEXTEDITING, "SDL_TEXTEDITING" },
        { SDL_TEXTINPUT, "SDL_TEXTINPUT" },
        { SDL_KEYMAPCHANGED, "SDL_KEYMAPCHANGED" },
        { SDL_TEXTEDITING_EXT, "SDL_TEXTEDITING_EXT" },
        { SDL_MOUSEMOTION, "SDL_MOUSEMOTION" },
        { SDL_MOUSEBUTTONDOWN, "SDL_MOUSEBUTTONDOWN" },
        { SDL_MOUSEBUTTONUP, "SDL_MOUSEBUTTONUP" },
        { SDL_MOUSEWHEEL, "SDL_MOUSEWHEEL" },
        { SDL_JOYAXISMOTION, "SDL_JOYAXISMOTION" },
        { SDL_JOYBALLMOTION, "SDL_JOYBALLMOTION" },
        { SDL_JOYHATMOTION, "SDL_JOYHATMOTION" },
        { SDL_JOYBUTTONDOWN, "SDL_JOYBUTTONDOWN" },
        { SDL_JOYBUTTONUP, "SDL_JOYBUTTONUP" },
        { SDL_JOYDEVICEADDED, "SDL_JOYDEVICEADDED" },
        { SDL_JOYDEVICEREMOVED, "SDL_JOYDEVICEREMOVED" },
        { SDL_JOYBATTERYUPDATED, "SDL_JOYBATTERYUPDATED" },
        { SDL_CONTROLLERAXISMOTION, "SDL_CONTROLLERAXISMOTION" },
        { SDL_CONTROLLERBUTTONDOWN, "SDL_CONTROLLERBUTTONDOWN" },
        { SDL_CONTROLLERBUTTONUP, "SDL_CONTROLLERBUTTONUP" },
        { SDL_CONTROLLERDEVICEADDED, "SDL_CONTROLLERDEVICEADDED" },
        { SDL_CONTROLLERDEVICEREMOVED, "SDL_CONTROLLERDEVICEREMOVED" },
        { SDL_CONTROLLERDEVICEREMAPPED, "SDL_CONTROLLERDEVICEREMAPPED" },
        { SDL_CONTROLLERTOUCHPADDOWN, "SDL_CONTROLLERTOUCHPADDOWN" },
        { SDL_CONTROLLERTOUCHPADMOTION, "SDL_CONTROLLERTOUCHPADMOTION" },
        { SDL_CONTROLLERTOUCHPADUP, "SDL_CONTROLLERTOUCHPADUP" },
        { SDL_CONTROLLERSENSORUPDATE, "SDL_CONTROLLERSENSORUPDATE" },
    #ifdef SDL_CONTROLLERUPDATECOMPLETE_RESERVED_FOR_SDL3
        { SDL_CONTROLLERUPDATECOMPLETE_RESERVED_FOR_SDL3, "SDL_CONTROLLERUPDATECOMPLETE_RESERVED_FOR_SDL3" },
    #endif
    #ifdef SDL_CONTROLLERSTEAMHANDLEUPDATED
        { SDL_CONTROLLERSTEAMHANDLEUPDATED, "SDL_CONTROLLERSTEAMHANDLEUPDATED" },
    #endif
        { SDL_FINGERDOWN,   "SDL_FINGERDOWN" },
        { SDL_FINGERUP,     "SDL_FINGERUP" },
        { SDL_FINGERMOTION, "SDL_FINGERMOTION" },
        { SDL_DOLLARGESTURE,"SDL_DOLLARGESTURE" },
        { SDL_DOLLARRECORD, "SDL_DOLLARRECORD" },
        { SDL_MULTIGESTURE, "SDL_MULTIGESTURE" },
        { SDL_CLIPBOARDUPDATE, "SDL_CLIPBOARDUPDATE" },
        { SDL_DROPFILE,        "SDL_DROPFILE" },
        { SDL_DROPTEXT,        "SDL_DROPTEXT" },
        { SDL_DROPBEGIN,       "SDL_DROPBEGIN" },
        { SDL_DROPCOMPLETE,    "SDL_DROPCOMPLETE" },
        { SDL_AUDIODEVICEADDED,"SDL_AUDIODEVICEADDED" },
        { SDL_AUDIODEVICEREMOVED, "SDL_AUDIODEVICEREMOVED" },
        { SDL_SENSORUPDATE,    "SDL_SENSORUPDATE" },
        { SDL_RENDER_TARGETS_RESET, "SDL_RENDER_TARGETS_RESET" },
        { SDL_RENDER_DEVICE_RESET, "SDL_RENDER_DEVICE_RESET" },
        { SDL_POLLSENTINEL,    "SDL_POLLSENTINEL" },
        { SDL_USEREVENT,       "SDL_USEREVENT" },   // base
        { SDL_LASTEVENT,       "SDL_LASTEVENT" }
    };
  #endif
  
  #define CCG_Main SDL_main
#endif
 
  